### PR TITLE
Character Counter on Input Fields

### LINKED ISSUE #647: Show character counts for expert answer boxes
The biggest piece of UI/UX feedback from the July 30th live experiments was that participants wanted to know how many characters they had used. Although they could copy/paste to an outside tool, we should be able to give them this info inside Mosaic. 

@zjmiller notes we could make use of the existing functionality that shows character counts on pointer tooltips.

Let's discuss how we want the character counter to look. Here is one before/after sketch:

image

image

If the workspace count got into the negatives, the counters would turn red. Thoughts? @brachbach @stuhlmueller

### PR DESCRIPTION
**Pull request by andrewschreiber**
closes #647

Character count display is ready. Need to add logic to only show on editable fields.

### CODE REVIEW

**Comment by andrewschreiber** [comment]
GIF of the counter in action.
ezgif com-video-to-gif
Ready for design feedback.

**Comment by andrewschreiber** [comment]
My expectation with `getLocalCharacterCount` was that it would require different logic from `getInputCharacterCount`, but it turned out to be redundant. PR cleaned up and ready for re-review.

**Comment by andrewschreiber** [comment]
I'll let you merge this one when you feel we're ready. I'm done making changes.

**Comment by Mati-Roy** [comment]
Suggestion from Erol related to this:
> perhaps a calculator on judge WS that shows the input budget that would remain once a judge receives your question + unfurls it

it got 5 :heart-eyes: here: https://app.slack.com/client/T3L8K3NMT/CKT7N2C83/thread/CKT7N2C83-1566583251.032600

**Comment by zjmiller** [comment]
Ok, so I modified the `inputCharCount` function to count each export as 1. Imports were already counted as 1.

**Comment by andrewschreiber** [comment]
@Mati-Roy Seems like a great UI idea. Will bring it up when I talk with ben next about priorities.

**Comment by Mati-Roy** [comment]
@andrewschreiber , Nicholas also wrote:
> As a ME sometimes it’s really helpful to figure out how many characters a subjudge will have after they open certain things, and it’s rather hard to figure this out now.  I’m not sure if it’s possible to fix this.

(ref.: https://app.slack.com/client/T3L8K3NMT/CKT7N2C83/thread/CKT7N2C83-1566834934.033800)

So an even better version of this feature might allow getting the character count with or without some pointers.

**Pull request merged**
