### PR TITLE
Style imports to look like exports

### PR DESCRIPTION
**Pull request by zjmiller**
See #154. This also addresses the comment in that issue about the extra space.

### CODE REVIEW

**Comment by zjmiller** [comment]
Also resolves #146, which is pretty much same as #154.

**Comment by stuhlmueller** [comment]
Looks like the build failed (for reasons that are not our fault, some package server unavailable).

**Comment by stuhlmueller** [comment]
Tried the app, it didn't look like it had the new style, checked heroku logs for [mosaic-prod](https://dashboard.heroku.com/apps/mosaic-prod), it said:

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=development
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  9.7.1
       engines.npm (package.json):   5.6.0
       
       Resolving node version 9.7.1...
       Downloading and installing node 9.7.1...
       npm 5.6.0 already installed with node
       Resolving yarn version 1.5.1...
       Downloading and installing yarn (1.5.1)...
       Installed yarn 1.5.1
       
-----> Restoring cache
       - node_modules (not cached - skipping)
       
-----> Building dependencies
       Running heroku-prebuild
       
       > mosaic@1.0.0 heroku-prebuild /tmp/build_f19eea5dbe1f8237efab0b47e3795fc5
       > HEROKU_BUILD=true && cd client && yarn install && yarn run build && cd ../server && yarn --production=false
       
       yarn install v1.5.1
       [1/4] Resolving packages...
       [2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/mkdirp/-/mkdirp-0.5.1.tgz: Request failed \"500 Internal Server Error\"".
       info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_f19eea5dbe1f8237efab0b47e3795fc5/client/yarn-error.log".
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mosaic@1.0.0 heroku-prebuild: `HEROKU_BUILD=true && cd client && yarn install && yarn run build && cd ../server && yarn --production=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mosaic@1.0.0 heroku-prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.mPKts/_logs/2018-09-11T22_54_01_363Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by OAGr** [comment]
Hm... We could revert it for now, then have @zjmiller or similar work it out. I don't believe I have access to the full deployment stack. If it's not urgent though, we could wait for him. 

If the build failed but the previous v. is still online, then that could be ok. you may also be able to rollback with heroku.

**Comment by zjmiller** [comment]
I'll try to rebuild.

**Comment by zjmiller** [comment]
Working now!

**Pull request merged**
