### PR TITLE
Allow experts to skip workspaces

### PR DESCRIPTION
**Pull request by zjmiller**

### CODE REVIEW

**Comment by andrewschreiber** [comment]
Instead of it's current, spot in the top center. I'm thinking the skip button could be in the `Answer Candidate` box, right aligned?

**Comment by andrewschreiber** [comment]
Current and target spot (black box). GitHub image uploading is down, so I had to use this: https://ibb.co/xDJpgkh

**Comment by andrewschreiber** [comment]
@brachbach @Mati-Roy Any UI feedback here?

**Comment by Mati-Roy** [comment]
I don't feel strongly one way or another.

**Pull request merged**
